name: seguros
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter         

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0

  intl: ^0.17.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.0.2+1
  http: ^0.13.1
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  extended_image: ^4.0.1

dev_dependencies:
  mobx_codegen:
  build_runner: 
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/json/atividades.json
    - assets/images/contratado.jpg

  uses-material-design: true
  generate: true

